name: highlighting_atoms
channels:
  - default
  - rdkit
  - conda-forge
dependencies:
  - more-itertools
  - pip
  - python
  - rdkit=2023.09.6
  - bokeh=3.1.1
  - scikit-learn
  - pip:
    - ipython
    - matplotlib
    - numpy
    - pandas
    - pyyaml
    - xlsxwriter

